### ISSUE TITLE
Install fails on php7.4

### ISSUE THREAD

**Issue by fleshgordo** [Diverently/anotherkit#20]
After running `php ./configure.php` I am getting:

`PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with()`

I think it's related to not running php8, but in the composer.json php requirements are stated as:

`"php": "^7.4|^8.0",`

hence I thought it should work with my current php version (PHP 7.4.27)

**Comment by RobertCordes** [comment]
Hey @fleshgordo, thanks for reporting this. I will see what I can do.

**Comment by RobertCordes** [comment]
Sorry @fleshgordo, that was my bad. I though `str_starts_with()` was already available in PHP 7.4, but it came with PHP 8. I have updated the PHP requirement to `^8.0`.
