### ISSUE TITLE
.editorconfig Kirby yaml defaults

### ISSUE THREAD

**Issue by iskrisis** [Diverently/anotherkit#9]
Hi, i've been using your kit because its super similar to mine https://github.com/floriankarsten/kirby3-mix-build-kit/tree/next and maybe there is no need to double the efforts.

Anyway your .editorconfig uses 4 spaces for .yml i find it a bit unfortunate because all the docs and majority of plugins follow something like this https://github.com/getkirby/starterkit/blob/master/.editorconfig and while i don't care about most of it (i use tabs) having YAML as 4 spaces little messes up with things when copying and trying to make things in broader community.

**Comment by RobertCordes** [comment]
Normally I would stick with the "community way" for sure, but I guess I’m too old now for 2 spaces 🤓 I need to see those indentations more clearly. But you can always change that after creating a new project!
